### ISSUE TITLE
Add to text breaking the app

### ISSUE THREAD

**Issue by johnmendez2** [layerhub-io/react-design-editor#101]
caught TypeError: Cannot read properties of undefined (reading 'family')
    at getTextProperties (text.ts:10:53)
    at Text.tsx:65:30
    at commitHookEffectListMount (react-dom.development.js:23150:26)

**Comment by 664215399** [comment]
me too

**Comment by shanmugapriyaasmurugesan** [comment]
Hi, I downloaded the repo and tried to run it. but when I run it, the index.html file is opening as a blank page. can you please help here?
